UPDATE S 
SET  
S.FLG_CONFIRMA_PERFIL_VENCIDO = T.FLG_CONFIRMA_PERFIL_VENCIDO, 
S.FLG_RENUNCIA_SUGERENCIA_PERFIL = T.FLG_RENUNCIA_SUGERENCIA_PERFIL,
S.FLG_AUTORIZACION_PROSPECTO = T.FLG_AUTORIZACION_PROSPECTO,
S.FLG_EXONERACION_RESPONSABILIDAD = T.FLG_EXONERACION_RESPONSABILIDAD, 
S.FLG_VINCULACION_DAVIVIENDA_CORREDORES = T.FLG_VINCULACION_DAVIVIENDA_CORREDORES,
S.FECHA_AUTORIZACION = T.FECHA_AUTORIZACION, 
S.HORA_AUTORIZACION = T.HORA_AUTORIZACION


FROM ${var:bd_temp}.temp_apertura_fic_trazabilidad_nrt S 

JOIN (
		SELECT 
		MAX(CASE WHEN JUR.tipo_documento ='confirmaPerfilVencido'  THEN 'Si' ELSE 'No' END) AS FLG_CONFIRMA_PERFIL_VENCIDO, 
		MAX(CASE WHEN JUR.tipo_documento ='renunciaSugerenciaPerfil'  THEN 'Si' ELSE 'No' END) AS FLG_RENUNCIA_SUGERENCIA_PERFIL, 
		MAX(CASE WHEN JUR.tipo_documento ='autorizacionProspecto'  THEN 'Si' ELSE 'No' END) AS FLG_AUTORIZACION_PROSPECTO, 
		MAX(CASE WHEN JUR.tipo_documento ='exoneracionDeResponsabilidad'  THEN 'Si' ELSE 'No' END) AS FLG_EXONERACION_RESPONSABILIDAD,
		MAX(CASE WHEN JUR.tipo_documento ='vinculacionDaviviendaCorredores'  THEN 'Si' ELSE 'No' END) AS FLG_VINCULACION_DAVIVIENDA_CORREDORES,
		MAX(CASE WHEN JUR.tipo_documento ='autorizacionProspecto' THEN TRUNC(JUR.FECHA_HORA_OPERACION,'dd')  END) AS FECHA_AUTORIZACION, 
   	    MAX(CASE WHEN JUR.tipo_documento ='autorizacionProspecto' THEN CAST(from_timestamp(JUR.FECHA_HORA_OPERACION,'HH:mm:ss') AS STRING) END) AS HORA_AUTORIZACION,  
		nro_id_sesion

		FROM ${var:bd_cruda}.mbaas_log_juridico jur  
		WHERE ID_APLICACION IN ('FIC')
		AND PERIODO = ${var:periodo_inicial}
		GROUP BY nro_id_sesion
	) T  

ON S.rgst_nro_solicitud = T.nro_id_sesion;